/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sudenaz_yıldırım_2221251033_networklab_2026;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicTextFieldUI;

/**
 *
 * @author ASUS
 */
public class startpage extends javax.swing.JFrame {

    /**
     * Creates new form startpage
     */
    public startpage() {
        initComponents();

        // BUTTON ŞEFFAF
        btnJoin.setText("");
        btnJoin.setBorder(null);
        btnJoin.setContentAreaFilled(false);
        btnJoin.setFocusPainted(false);
        btnJoin.setOpaque(false);

        // TEXTFIELD ŞEFFAF
        makeTransparent(nametxt);
        makeTransparent(Iptxt);
        makeTransparent(porttxt);

        // PLACEHOLDER
        setPlaceholder(nametxt, "  ");
        setPlaceholder(Iptxt, " ");
        setPlaceholder(porttxt, "  ");

    }

    private void setPlaceholder(javax.swing.JTextField field, String placeholder) {

        field.setForeground(Color.GRAY);
        field.setText(placeholder);

        field.addFocusListener(new java.awt.event.FocusAdapter() {

            @Override
            public void focusGained(java.awt.event.FocusEvent e) {

                if (field.getText().equals(placeholder)) {
                    field.setText("");
                    field.setForeground(Color.WHITE);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {

                if (field.getText().isEmpty()) {
                    field.setForeground(Color.GRAY);
                    field.setText(placeholder);
                }
            }
        });
    }

    private void makeTransparent(javax.swing.JTextField field) {
        field.setOpaque(false);
        field.setBackground(new Color(0, 0, 0, 0));
        field.setBorder(BorderFactory.createEmptyBorder(0, 10, 0, 10));
        field.setForeground(Color.WHITE);
        field.setCaretColor(Color.WHITE);
        field.setUI(new BasicTextFieldUI());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nametxt = new javax.swing.JTextField();
        Iptxt = new javax.swing.JTextField();
        porttxt = new javax.swing.JTextField();
        btnJoin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nametxt.setText("jTextField1");
        jPanel1.add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 210, -1));

        Iptxt.setText("jTextField2");
        jPanel1.add(Iptxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 220, -1));

        porttxt.setText("jTextField3");
        jPanel1.add(porttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 210, -1));

        btnJoin.setBorderPainted(false);
        btnJoin.setContentAreaFilled(false);
        btnJoin.setFocusPainted(false);
        btnJoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJoinActionPerformed(evt);
            }
        });
        jPanel1.add(btnJoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 200, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/start_page1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJoinActionPerformed

    String name = nametxt.getText().trim();
    String ip = Iptxt.getText().trim();
    String port = porttxt.getText().trim();

    // NAME CONTROL
    if (name.isEmpty() || name.equals("Enter your name...")) {
        JOptionPane.showMessageDialog(this,
                "Please enter your name.");
        return;
    }

    // IP CONTROL
    if (ip.isEmpty() || ip.equals("Enter IP address...")) {
        JOptionPane.showMessageDialog(this,
                "Please enter server IP address.");
        return;
    }

   // PORT CONTROL
if (port.isEmpty()) {
    JOptionPane.showMessageDialog(this,
            "Please enter port number.");
    return;
}

    // PORT NUMBER CONTROL
    try {

        int portNumber = Integer.parseInt(port);

        // CONNECT TO SERVER
        ChessClient client =
                new ChessClient(ip, portNumber);

        // OPEN GAME SCREEN
        game g = new game(client);
        g.setVisible(true);

        // CLOSE START PAGE
        this.dispose();

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(this,
                "Port must be numeric.");

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
                "Could not connect to server.\n"
                + e.getMessage());
    }


    }//GEN-LAST:event_btnJoinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(startpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(startpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(startpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(startpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new startpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Iptxt;
    private javax.swing.JButton btnJoin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nametxt;
    private javax.swing.JTextField porttxt;
    // End of variables declaration//GEN-END:variables
}
